spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: STUDENT-SERVICE
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/students/**

        - id: MENTOR-SERVICE
          uri: lb://MENTOR-SERVICE
          predicates:
            - Path=/mentors/**

        - id: COURSE-SERVICE
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/courses/**,/courses-students/**
  config:
    import: configserver:http://localhost:8080
server:
  port: 8081
